//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  site: Site;
  siteConnection: SiteConnection;
  home: Home;
  homeConnection: HomeConnection;
  page: Page;
  pageConnection: PageConnection;
  event: Event;
  eventConnection: EventConnection;
  ministry: Ministry;
  ministryConnection: MinistryConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryEventArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventFilter>;
};


export type QueryMinistryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMinistryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MinistryFilter>;
};

export type DocumentFilter = {
  site?: InputMaybe<SiteFilter>;
  home?: InputMaybe<HomeFilter>;
  page?: InputMaybe<PageFilter>;
  event?: InputMaybe<EventFilter>;
  ministry?: InputMaybe<MinistryFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Site | Home | Page | Event | Ministry | Folder;

export type Site = Node & Document & {
  __typename?: 'Site';
  churchName: Scalars['String']['output'];
  tagline?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  sundayTime?: Maybe<Scalars['String']['output']>;
  facebookUrl?: Maybe<Scalars['String']['output']>;
  youtubeUrl?: Maybe<Scalars['String']['output']>;
  givingUrl?: Maybe<Scalars['String']['output']>;
  mailingListUrl?: Maybe<Scalars['String']['output']>;
  footerNote?: Maybe<Scalars['String']['output']>;
  seoDescription?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteFilter = {
  churchName?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  sundayTime?: InputMaybe<StringFilter>;
  facebookUrl?: InputMaybe<StringFilter>;
  youtubeUrl?: InputMaybe<StringFilter>;
  givingUrl?: InputMaybe<StringFilter>;
  mailingListUrl?: InputMaybe<StringFilter>;
  footerNote?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  headline: Scalars['String']['output'];
  eyebrow?: Maybe<Scalars['String']['output']>;
  subheadline?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  primaryButtonLabel?: Maybe<Scalars['String']['output']>;
  primaryButtonUrl?: Maybe<Scalars['String']['output']>;
  secondaryButtonLabel?: Maybe<Scalars['String']['output']>;
  secondaryButtonUrl?: Maybe<Scalars['String']['output']>;
  welcomeHeading?: Maybe<Scalars['String']['output']>;
  welcomeText?: Maybe<Scalars['String']['output']>;
  serviceHeading?: Maybe<Scalars['String']['output']>;
  serviceText?: Maybe<Scalars['String']['output']>;
  serviceButtonLabel?: Maybe<Scalars['String']['output']>;
  serviceButtonUrl?: Maybe<Scalars['String']['output']>;
  outreachHeading?: Maybe<Scalars['String']['output']>;
  outreachText?: Maybe<Scalars['String']['output']>;
  outreachButtonLabel?: Maybe<Scalars['String']['output']>;
  outreachButtonUrl?: Maybe<Scalars['String']['output']>;
  closingHeading?: Maybe<Scalars['String']['output']>;
  closingText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeFilter = {
  headline?: InputMaybe<StringFilter>;
  eyebrow?: InputMaybe<StringFilter>;
  subheadline?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  primaryButtonLabel?: InputMaybe<StringFilter>;
  primaryButtonUrl?: InputMaybe<StringFilter>;
  secondaryButtonLabel?: InputMaybe<StringFilter>;
  secondaryButtonUrl?: InputMaybe<StringFilter>;
  welcomeHeading?: InputMaybe<StringFilter>;
  welcomeText?: InputMaybe<StringFilter>;
  serviceHeading?: InputMaybe<StringFilter>;
  serviceText?: InputMaybe<StringFilter>;
  serviceButtonLabel?: InputMaybe<StringFilter>;
  serviceButtonUrl?: InputMaybe<StringFilter>;
  outreachHeading?: InputMaybe<StringFilter>;
  outreachText?: InputMaybe<StringFilter>;
  outreachButtonLabel?: InputMaybe<StringFilter>;
  outreachButtonUrl?: InputMaybe<StringFilter>;
  closingHeading?: InputMaybe<StringFilter>;
  closingText?: InputMaybe<StringFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type PageSections = {
  __typename?: 'PageSections';
  heading: Scalars['String']['output'];
  anchor?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  eyebrow?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<PageSections>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  anchor?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  eyebrow?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  sections?: InputMaybe<PageSectionsFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Event = Node & Document & {
  __typename?: 'Event';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  date: Scalars['String']['output'];
  time?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  details?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  buttonLabel?: Maybe<Scalars['String']['output']>;
  buttonUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  time?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  details?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  featured?: InputMaybe<BooleanFilter>;
  buttonLabel?: InputMaybe<StringFilter>;
  buttonUrl?: InputMaybe<StringFilter>;
};

export type EventConnectionEdges = {
  __typename?: 'EventConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Event>;
};

export type EventConnection = Connection & {
  __typename?: 'EventConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventConnectionEdges>>>;
};

export type Ministry = Node & Document & {
  __typename?: 'Ministry';
  title: Scalars['String']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  sortOrder?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type MinistryFilter = {
  title?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  featured?: InputMaybe<BooleanFilter>;
  sortOrder?: InputMaybe<NumberFilter>;
};

export type MinistryConnectionEdges = {
  __typename?: 'MinistryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Ministry>;
};

export type MinistryConnection = Connection & {
  __typename?: 'MinistryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MinistryConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSite: Site;
  createSite: Site;
  updateHome: Home;
  createHome: Home;
  updatePage: Page;
  createPage: Page;
  updateEvent: Event;
  createEvent: Event;
  updateMinistry: Ministry;
  createMinistry: Ministry;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationCreateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationUpdateMinistryArgs = {
  relativePath: Scalars['String']['input'];
  params: MinistryMutation;
};


export type MutationCreateMinistryArgs = {
  relativePath: Scalars['String']['input'];
  params: MinistryMutation;
};

export type DocumentUpdateMutation = {
  site?: InputMaybe<SiteMutation>;
  home?: InputMaybe<HomeMutation>;
  page?: InputMaybe<PageMutation>;
  event?: InputMaybe<EventMutation>;
  ministry?: InputMaybe<MinistryMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  site?: InputMaybe<SiteMutation>;
  home?: InputMaybe<HomeMutation>;
  page?: InputMaybe<PageMutation>;
  event?: InputMaybe<EventMutation>;
  ministry?: InputMaybe<MinistryMutation>;
};

export type SiteMutation = {
  churchName?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  sundayTime?: InputMaybe<Scalars['String']['input']>;
  facebookUrl?: InputMaybe<Scalars['String']['input']>;
  youtubeUrl?: InputMaybe<Scalars['String']['input']>;
  givingUrl?: InputMaybe<Scalars['String']['input']>;
  mailingListUrl?: InputMaybe<Scalars['String']['input']>;
  footerNote?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  subheadline?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  primaryButtonLabel?: InputMaybe<Scalars['String']['input']>;
  primaryButtonUrl?: InputMaybe<Scalars['String']['input']>;
  secondaryButtonLabel?: InputMaybe<Scalars['String']['input']>;
  secondaryButtonUrl?: InputMaybe<Scalars['String']['input']>;
  welcomeHeading?: InputMaybe<Scalars['String']['input']>;
  welcomeText?: InputMaybe<Scalars['String']['input']>;
  serviceHeading?: InputMaybe<Scalars['String']['input']>;
  serviceText?: InputMaybe<Scalars['String']['input']>;
  serviceButtonLabel?: InputMaybe<Scalars['String']['input']>;
  serviceButtonUrl?: InputMaybe<Scalars['String']['input']>;
  outreachHeading?: InputMaybe<Scalars['String']['input']>;
  outreachText?: InputMaybe<Scalars['String']['input']>;
  outreachButtonLabel?: InputMaybe<Scalars['String']['input']>;
  outreachButtonUrl?: InputMaybe<Scalars['String']['input']>;
  closingHeading?: InputMaybe<Scalars['String']['input']>;
  closingText?: InputMaybe<Scalars['String']['input']>;
};

export type PageSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  anchor?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<PageSectionsMutation>>>;
};

export type EventMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  buttonLabel?: InputMaybe<Scalars['String']['input']>;
  buttonUrl?: InputMaybe<Scalars['String']['input']>;
};

export type MinistryMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  sortOrder?: InputMaybe<Scalars['Float']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type SiteFilter = {
  churchName?: StringFilter | null | undefined;
  tagline?: StringFilter | null | undefined;
  address?: StringFilter | null | undefined;
  phone?: StringFilter | null | undefined;
  email?: StringFilter | null | undefined;
  sundayTime?: StringFilter | null | undefined;
  facebookUrl?: StringFilter | null | undefined;
  youtubeUrl?: StringFilter | null | undefined;
  givingUrl?: StringFilter | null | undefined;
  mailingListUrl?: StringFilter | null | undefined;
  footerNote?: StringFilter | null | undefined;
  seoDescription?: StringFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type HomeFilter = {
  headline?: StringFilter | null | undefined;
  eyebrow?: StringFilter | null | undefined;
  subheadline?: StringFilter | null | undefined;
  heroImage?: ImageFilter | null | undefined;
  primaryButtonLabel?: StringFilter | null | undefined;
  primaryButtonUrl?: StringFilter | null | undefined;
  secondaryButtonLabel?: StringFilter | null | undefined;
  secondaryButtonUrl?: StringFilter | null | undefined;
  welcomeHeading?: StringFilter | null | undefined;
  welcomeText?: StringFilter | null | undefined;
  serviceHeading?: StringFilter | null | undefined;
  serviceText?: StringFilter | null | undefined;
  serviceButtonLabel?: StringFilter | null | undefined;
  serviceButtonUrl?: StringFilter | null | undefined;
  outreachHeading?: StringFilter | null | undefined;
  outreachText?: StringFilter | null | undefined;
  outreachButtonLabel?: StringFilter | null | undefined;
  outreachButtonUrl?: StringFilter | null | undefined;
  closingHeading?: StringFilter | null | undefined;
  closingText?: StringFilter | null | undefined;
};

export type PageSectionsFilter = {
  heading?: StringFilter | null | undefined;
  anchor?: StringFilter | null | undefined;
  text?: StringFilter | null | undefined;
};

export type PageFilter = {
  title?: StringFilter | null | undefined;
  eyebrow?: StringFilter | null | undefined;
  intro?: StringFilter | null | undefined;
  sections?: PageSectionsFilter | null | undefined;
};

export type DatetimeFilter = {
  after?: string | null | undefined;
  before?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type EventFilter = {
  title?: StringFilter | null | undefined;
  slug?: StringFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  time?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
  summary?: StringFilter | null | undefined;
  details?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  featured?: BooleanFilter | null | undefined;
  buttonLabel?: StringFilter | null | undefined;
  buttonUrl?: StringFilter | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type MinistryFilter = {
  title?: StringFilter | null | undefined;
  summary?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  featured?: BooleanFilter | null | undefined;
  sortOrder?: NumberFilter | null | undefined;
};

export type SitePartsFragment = { __typename: 'Site', churchName: string, tagline: string | null, address: string | null, phone: string | null, email: string | null, sundayTime: string | null, facebookUrl: string | null, youtubeUrl: string | null, givingUrl: string | null, mailingListUrl: string | null, footerNote: string | null, seoDescription: string | null };

export type HomePartsFragment = { __typename: 'Home', headline: string, eyebrow: string | null, subheadline: string | null, heroImage: string | null, primaryButtonLabel: string | null, primaryButtonUrl: string | null, secondaryButtonLabel: string | null, secondaryButtonUrl: string | null, welcomeHeading: string | null, welcomeText: string | null, serviceHeading: string | null, serviceText: string | null, serviceButtonLabel: string | null, serviceButtonUrl: string | null, outreachHeading: string | null, outreachText: string | null, outreachButtonLabel: string | null, outreachButtonUrl: string | null, closingHeading: string | null, closingText: string | null };

export type PagePartsFragment = { __typename: 'Page', title: string, eyebrow: string | null, intro: string | null, sections: Array<{ __typename: 'PageSections', heading: string, anchor: string | null, text: string | null } | null> | null };

export type EventPartsFragment = { __typename: 'Event', title: string, slug: string, date: string, time: string | null, location: string | null, summary: string | null, details: string | null, image: string | null, featured: boolean | null, buttonLabel: string | null, buttonUrl: string | null };

export type MinistryPartsFragment = { __typename: 'Ministry', title: string, summary: string | null, description: string | null, image: string | null, featured: boolean | null, sortOrder: number | null };

export type SiteQueryVariables = Exact<{
  relativePath: string;
}>;


export type SiteQuery = { site: { __typename: 'Site', id: string, churchName: string, tagline: string | null, address: string | null, phone: string | null, email: string | null, sundayTime: string | null, facebookUrl: string | null, youtubeUrl: string | null, givingUrl: string | null, mailingListUrl: string | null, footerNote: string | null, seoDescription: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SiteConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: SiteFilter | null | undefined;
}>;


export type SiteConnectionQuery = { siteConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Site', id: string, churchName: string, tagline: string | null, address: string | null, phone: string | null, email: string | null, sundayTime: string | null, facebookUrl: string | null, youtubeUrl: string | null, givingUrl: string | null, mailingListUrl: string | null, footerNote: string | null, seoDescription: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomeQueryVariables = Exact<{
  relativePath: string;
}>;


export type HomeQuery = { home: { __typename: 'Home', id: string, headline: string, eyebrow: string | null, subheadline: string | null, heroImage: string | null, primaryButtonLabel: string | null, primaryButtonUrl: string | null, secondaryButtonLabel: string | null, secondaryButtonUrl: string | null, welcomeHeading: string | null, welcomeText: string | null, serviceHeading: string | null, serviceText: string | null, serviceButtonLabel: string | null, serviceButtonUrl: string | null, outreachHeading: string | null, outreachText: string | null, outreachButtonLabel: string | null, outreachButtonUrl: string | null, closingHeading: string | null, closingText: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HomeConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: HomeFilter | null | undefined;
}>;


export type HomeConnectionQuery = { homeConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Home', id: string, headline: string, eyebrow: string | null, subheadline: string | null, heroImage: string | null, primaryButtonLabel: string | null, primaryButtonUrl: string | null, secondaryButtonLabel: string | null, secondaryButtonUrl: string | null, welcomeHeading: string | null, welcomeText: string | null, serviceHeading: string | null, serviceText: string | null, serviceButtonLabel: string | null, serviceButtonUrl: string | null, outreachHeading: string | null, outreachText: string | null, outreachButtonLabel: string | null, outreachButtonUrl: string | null, closingHeading: string | null, closingText: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PageQueryVariables = Exact<{
  relativePath: string;
}>;


export type PageQuery = { page: { __typename: 'Page', id: string, title: string, eyebrow: string | null, intro: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections: Array<{ __typename: 'PageSections', heading: string, anchor: string | null, text: string | null } | null> | null } };

export type PageConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PageFilter | null | undefined;
}>;


export type PageConnectionQuery = { pageConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Page', id: string, title: string, eyebrow: string | null, intro: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections: Array<{ __typename: 'PageSections', heading: string, anchor: string | null, text: string | null } | null> | null } | null } | null> | null } };

export type EventQueryVariables = Exact<{
  relativePath: string;
}>;


export type EventQuery = { event: { __typename: 'Event', id: string, title: string, slug: string, date: string, time: string | null, location: string | null, summary: string | null, details: string | null, image: string | null, featured: boolean | null, buttonLabel: string | null, buttonUrl: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: EventFilter | null | undefined;
}>;


export type EventConnectionQuery = { eventConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Event', id: string, title: string, slug: string, date: string, time: string | null, location: string | null, summary: string | null, details: string | null, image: string | null, featured: boolean | null, buttonLabel: string | null, buttonUrl: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MinistryQueryVariables = Exact<{
  relativePath: string;
}>;


export type MinistryQuery = { ministry: { __typename: 'Ministry', id: string, title: string, summary: string | null, description: string | null, image: string | null, featured: boolean | null, sortOrder: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MinistryConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: MinistryFilter | null | undefined;
}>;


export type MinistryConnectionQuery = { ministryConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Ministry', id: string, title: string, summary: string | null, description: string | null, image: string | null, featured: boolean | null, sortOrder: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  churchName
  tagline
  address
  phone
  email
  sundayTime
  facebookUrl
  youtubeUrl
  givingUrl
  mailingListUrl
  footerNote
  seoDescription
}
    `;
export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  headline
  eyebrow
  subheadline
  heroImage
  primaryButtonLabel
  primaryButtonUrl
  secondaryButtonLabel
  secondaryButtonUrl
  welcomeHeading
  welcomeText
  serviceHeading
  serviceText
  serviceButtonLabel
  serviceButtonUrl
  outreachHeading
  outreachText
  outreachButtonLabel
  outreachButtonUrl
  closingHeading
  closingText
}
    `;
export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  eyebrow
  intro
  sections {
    __typename
    heading
    anchor
    text
  }
}
    `;
export const EventPartsFragmentDoc = gql`
    fragment EventParts on Event {
  __typename
  title
  slug
  date
  time
  location
  summary
  details
  image
  featured
  buttonLabel
  buttonUrl
}
    `;
export const MinistryPartsFragmentDoc = gql`
    fragment MinistryParts on Ministry {
  __typename
  title
  summary
  description
  image
  featured
  sortOrder
}
    `;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const EventDocument = gql`
    query event($relativePath: String!) {
  event(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventParts
  }
}
    ${EventPartsFragmentDoc}`;
export const EventConnectionDocument = gql`
    query eventConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventFilter) {
  eventConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventParts
      }
    }
  }
}
    ${EventPartsFragmentDoc}`;
export const MinistryDocument = gql`
    query ministry($relativePath: String!) {
  ministry(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MinistryParts
  }
}
    ${MinistryPartsFragmentDoc}`;
export const MinistryConnectionDocument = gql`
    query ministryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MinistryFilter) {
  ministryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MinistryParts
      }
    }
  }
}
    ${MinistryPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      },
    home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    event(variables: EventQueryVariables, options?: C): Promise<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}> {
        return requester<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}, EventQueryVariables>(EventDocument, variables, options);
      },
    eventConnection(variables?: EventConnectionQueryVariables, options?: C): Promise<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}> {
        return requester<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}, EventConnectionQueryVariables>(EventConnectionDocument, variables, options);
      },
    ministry(variables: MinistryQueryVariables, options?: C): Promise<{data: MinistryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MinistryQueryVariables, query: string}> {
        return requester<{data: MinistryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MinistryQueryVariables, query: string}, MinistryQueryVariables>(MinistryDocument, variables, options);
      },
    ministryConnection(variables?: MinistryConnectionQueryVariables, options?: C): Promise<{data: MinistryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MinistryConnectionQueryVariables, query: string}> {
        return requester<{data: MinistryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MinistryConnectionQueryVariables, query: string}, MinistryConnectionQueryVariables>(MinistryConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  